version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neo_watcher
    ports:
      - "5432:5432"
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
