name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8
      - name: Check formatting
        run: black --check .
      - name: Type-check with mypy
        run: mypy app
      - name: Run tests with coverage
        run: pytest --cov --cov-fail-under=100
      - name: Install Node dependencies
        run: npm ci
      - name: Run UI tests
        run: |
          npx playwright install --with-deps
          npx playwright test
      - name: Build Docker image
        run: docker build . -t ${{ github.repository }}:${{ github.sha }} --no-cache
      # - name: Push Docker image
      #   run: |
      #     echo "docker login and push commands go here"
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform -chdir=terraform init
      - name: Terraform validate
        run: terraform -chdir=terraform validate
      - name: Terraform plan
        run: terraform -chdir=terraform plan -out=tfplan
      - name: Terraform apply
        run: terraform -chdir=terraform apply -auto-approve tfplan
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to Cloud Run
        run: gcloud run deploy neo-watcher --source . --no-promote --region=us-central1 --platform=managed
